### ISSUE TITLE
Mixing columns

### ISSUE THREAD

**Issue by basheerKhagga** [mayank-02/simplified-aes#1]
It seems as if the output of the function mix_columns() is different than what we get upon multiplying the given matrix with 
{1    4}
{4    1}
and then looking up values from the standard multiplication table.
I just can't believe that output of this code would be wrong so I'm curious if there is another justification.

![multiplication_lookup_table](https://user-images.githubusercontent.com/95972140/196124293-cdd29bcc-a934-4b58-8bfa-23e95d4fb49e.jpg)

**Comment by mayank-02** [comment]
The [example](https://github.com/mayank-02/simplified-aes/blob/main/README.md#usage) in the README is borrowed from https://sandilands.info/sgordon/teaching/reports/simplified-aes-example.pdf. Can you see if this helps answer your question?

**Comment by basheerKhagga** [comment]
Yes, it was my fault, as expected. Your program is great. I had to modify some functions to print different outcomes otherwise it is perfect. And those return values of functions 🤯
